import type { Car } from '../types';

export const mockCars: Car[] = [
  {
    id: 'car-001',
    model: 'Model 3',
    brand: 'Tesla',
    plate: 'ELT-0001',
    batteryLevel: 87,
    autonomy: 520,
    status: 'available',
    location: 'Zona Norte',
    pricePerDay: 180,
    pricePerWeek: 980,
    image: '🚗',
    features: ['Autopilot', 'Aquecimento', 'USB-C'],
    utilizationRate: 78,
  },
  {
    id: 'car-002',
    model: 'BYD Dolphin',
    brand: 'BYD',
    plate: 'ELT-0002',
    batteryLevel: 45,
    autonomy: 240,
    status: 'in_use',
    location: 'Centro',
    pricePerDay: 120,
    pricePerWeek: 650,
    image: '🚙',
    features: ['CarPlay', 'Câmera 360', 'Fast Charge'],
    utilizationRate: 92,
  },
  {
    id: 'car-003',
    model: 'Argo Electric',
    brand: 'Fiat',
    plate: 'ELT-0003',
    batteryLevel: 95,
    autonomy: 380,
    status: 'available',
    location: 'Zona Sul',
    pricePerDay: 140,
    pricePerWeek: 760,
    image: '🚕',
    features: ['Android Auto', 'Ar Condicionado', 'Seguro Incluso'],
    utilizationRate: 65,
  },
  {
    id: 'car-004',
    model: 'GWM Ora 03',
    brand: 'GWM',
    plate: 'ELT-0004',
    batteryLevel: 62,
    autonomy: 290,
    status: 'reserved',
    location: 'Zona Leste',
    pricePerDay: 130,
    pricePerWeek: 710,
    image: '🚘',
    features: ['Teto Solar', 'Fast Charge', 'Câmera Ré'],
    utilizationRate: 83,
  },
  {
    id: 'car-005',
    model: 'Bolt EV',
    brand: 'Chevrolet',
    plate: 'ELT-0005',
    batteryLevel: 15,
    autonomy: 70,
    status: 'maintenance',
    location: 'Garagem Central',
    pricePerDay: 150,
    pricePerWeek: 820,
    image: '🏎️',
    features: ['One Pedal Drive', 'Surround Vision', 'WiFi'],
    utilizationRate: 41,
  },
  {
    id: 'car-006',
    model: 'HB20 Elétrico',
    brand: 'Hyundai',
    plate: 'ELT-0006',
    batteryLevel: 78,
    autonomy: 350,
    status: 'available',
    location: 'Zona Oeste',
    pricePerDay: 135,
    pricePerWeek: 730,
    image: '🚗',
    features: ['V2L', 'ADAS', 'Aquecedor Banco'],
    utilizationRate: 71,
  },
];
