import type { ChargingStation } from '../types';

export const mockStations: ChargingStation[] = [
  {
    id: 'stn-001',
    name: 'VoltHub Centro',
    address: 'Av. Paulista, 1000 — Centro',
    status: 'free',
    connectors: 6,
    availableConnectors: 4,
    pricePerKwh: 1.2,
    isPeak: true,
    lat: -23.5629,
    lng: -46.6544,
    operatingHours: '06:00 – 23:00',
    utilizationRate: 74,
  },
  {
    id: 'stn-002',
    name: 'VoltHub Zona Norte',
    address: 'Rua das Laranjeiras, 250 — Zona Norte',
    status: 'occupied',
    connectors: 4,
    availableConnectors: 0,
    pricePerKwh: 0.9,
    isPeak: false,
    lat: -23.5200,
    lng: -46.6340,
    operatingHours: '00:00 – 24:00',
    utilizationRate: 88,
  },
  {
    id: 'stn-003',
    name: 'VoltHub Shopping Sul',
    address: 'Av. Santo Amaro, 2100 — Zona Sul',
    status: 'free',
    connectors: 8,
    availableConnectors: 6,
    pricePerKwh: 0.75,
    isPeak: false,
    lat: -23.6300,
    lng: -46.6900,
    operatingHours: '08:00 – 22:00',
    utilizationRate: 45,
  },
  {
    id: 'stn-004',
    name: 'VoltHub Leste Express',
    address: 'Rua Vergueiro, 3400 — Zona Leste',
    status: 'reserved',
    connectors: 4,
    availableConnectors: 1,
    pricePerKwh: 1.4,
    isPeak: true,
    lat: -23.5800,
    lng: -46.5900,
    operatingHours: '06:00 – 22:00',
    utilizationRate: 91,
  },
  {
    id: 'stn-005',
    name: 'VoltHub Garagem Central',
    address: 'Rua da Consolação, 700 — Centro',
    status: 'free',
    connectors: 12,
    availableConnectors: 9,
    pricePerKwh: 0.8,
    isPeak: false,
    lat: -23.5530,
    lng: -46.6560,
    operatingHours: '00:00 – 24:00',
    utilizationRate: 55,
  },
];
